name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read
  packages: write

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    container:
      image: node:22-alpine
    steps:
      - uses: actions/checkout@v5

      - run: npm ci

      - run: npm run lint

      - run: npm run build

  docker:
    runs-on: ubuntu-latest
    container:
      image: docker:28-cli
      options: --volume /var/run/docker.sock:/var/run/docker.sock
    steps:
      - uses: actions/checkout@v5

      - uses: docker/login-action@v3
        if: github.ref == 'refs/heads/master'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: ghcr.io/${{ github.repository }}:latest
